[INFO] 06-11-2023 14:54:17 [TestNG-PoolService-0] [APITest] - Test started : TC01- Add book api test
[INFO] 06-11-2023 14:54:18 [TestNG-PoolService-0] [APITest] - Test started : TC02- Get book api test
[INFO] 06-11-2023 14:54:18 [TestNG-PoolService-0] [APITest] - Test started : TC03- Delete book api test
[INFO] 06-11-2023 14:55:43 [main] [baseTestAPI] - java.lang.NullPointerException: Cannot invoke "io.restassured.specification.RequestSpecification.filter(io.restassured.filter.Filter)" because "this.req" is null
	at testCases.APITest.afterMethodLogging(APITest.java:86)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

[INFO] 06-11-2023 14:55:43 [TestNG-PoolService-0] [APITest] - Test started : TC01- Add book api test
[INFO] 06-11-2023 14:55:44 [TestNG-PoolService-0] [baseTestAPI] - java.lang.AssertionError: 1 expectation failed.
Expected status code <201> but was <200>.

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at io.restassured.internal.ResponseSpecificationImpl.validate(ResponseSpecificationImpl.groovy:101)
	at io.restassured.internal.ValidatableResponseOptionsImpl.spec(ValidatableResponseOptionsImpl.java:288)
	at testCases.APITest.addBookTest(APITest.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 06-11-2023 14:55:44 [TestNG-PoolService-0] [APITest] - Test started : TC02- Get book api test
[INFO] 06-11-2023 14:55:44 [TestNG-PoolService-0] [baseTestAPI] - java.lang.AssertionError: 1 expectation failed.
Expected status code <201> but was <404>.

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validate(ResponseSpecificationImpl.groovy:101)
	at io.restassured.internal.ValidatableResponseOptionsImpl.spec(ValidatableResponseOptionsImpl.java:288)
	at testCases.APITest.getBookByID(APITest.java:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 06-11-2023 14:55:44 [TestNG-PoolService-0] [APITest] - Test started : TC03- Delete book api test
[INFO] 06-11-2023 14:55:44 [TestNG-PoolService-0] [baseTestAPI] - java.lang.AssertionError: 1 expectation failed.
Expected status code <201> but was <404>.

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validate(ResponseSpecificationImpl.groovy:101)
	at io.restassured.internal.ValidatableResponseOptionsImpl.spec(ValidatableResponseOptionsImpl.java:288)
	at testCases.APITest.DeleteBook(APITest.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 06-11-2023 15:09:34 [TestNG-PoolService-0] [baseTestAPI] - java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.info(String)" because the return value of "reports.ExtentTestManager.getExtentTest()" is null
	at reports.ExtentReportManager.info(ExtentReportManager.java:60)
	at testCases.APITest.addBookTest(APITest.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 06-11-2023 15:09:34 [TestNG-PoolService-0] [baseTestAPI] - java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.info(String)" because the return value of "reports.ExtentTestManager.getExtentTest()" is null
	at reports.ExtentReportManager.info(ExtentReportManager.java:60)
	at testCases.APITest.getBookByID(APITest.java:68)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 06-11-2023 15:09:34 [TestNG-PoolService-0] [baseTestAPI] - java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.info(String)" because the return value of "reports.ExtentTestManager.getExtentTest()" is null
	at reports.ExtentReportManager.info(ExtentReportManager.java:60)
	at testCases.APITest.DeleteBook(APITest.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 06-11-2023 15:15:45 [TestNG-PoolService-0] [baseTestAPI] - java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.info(String)" because the return value of "reports.ExtentTestManager.getExtentTest()" is null
	at reports.ExtentReportManager.info(ExtentReportManager.java:60)
	at testCases.APITest.addBookTest(APITest.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 06-11-2023 15:15:45 [TestNG-PoolService-0] [baseTestAPI] - java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.info(String)" because the return value of "reports.ExtentTestManager.getExtentTest()" is null
	at reports.ExtentReportManager.info(ExtentReportManager.java:60)
	at testCases.APITest.getBookByID(APITest.java:68)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 06-11-2023 15:15:45 [TestNG-PoolService-0] [baseTestAPI] - java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.info(String)" because the return value of "reports.ExtentTestManager.getExtentTest()" is null
	at reports.ExtentReportManager.info(ExtentReportManager.java:60)
	at testCases.APITest.DeleteBook(APITest.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 06-11-2023 15:28:11 [main] [Log] - Suite started: Default suite
[INFO] 06-11-2023 15:28:12 [TestNG-PoolService-0] [Log] - addBookTest test case started
[INFO] 06-11-2023 15:28:12 [TestNG-PoolService-0] [APITest] - Test started : TC01- Add book api test
[ERROR] 06-11-2023 15:28:13 [TestNG-PoolService-0] [Log] - Test case: addBookTest is failed.
[INFO] 06-11-2023 15:28:13 [TestNG-PoolService-0] [baseTestAPI] - java.lang.AssertionError: expected [successfully added] but found [Book Already Exists]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:617)
	at testCases.APITest.addBookTest(APITest.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 06-11-2023 15:28:13 [TestNG-PoolService-0] [Log] - getBookByID test case started
[INFO] 06-11-2023 15:28:13 [TestNG-PoolService-0] [APITest] - Test started : TC02- Get book api test
[ERROR] 06-11-2023 15:28:14 [TestNG-PoolService-0] [Log] - Test case: getBookByID is failed.
[INFO] 06-11-2023 15:28:14 [TestNG-PoolService-0] [baseTestAPI] - java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validate(ResponseSpecificationImpl.groovy:101)
	at io.restassured.internal.ValidatableResponseOptionsImpl.spec(ValidatableResponseOptionsImpl.java:288)
	at testCases.APITest.getBookByID(APITest.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 06-11-2023 15:28:14 [TestNG-PoolService-0] [Log] - DeleteBook test case started
[INFO] 06-11-2023 15:28:14 [TestNG-PoolService-0] [APITest] - Test started : TC03- Delete book api test
[ERROR] 06-11-2023 15:28:14 [TestNG-PoolService-0] [Log] - Test case: DeleteBook is failed.
[INFO] 06-11-2023 15:28:14 [TestNG-PoolService-0] [baseTestAPI] - java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validate(ResponseSpecificationImpl.groovy:101)
	at io.restassured.internal.ValidatableResponseOptionsImpl.spec(ValidatableResponseOptionsImpl.java:288)
	at testCases.APITest.DeleteBook(APITest.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 06-11-2023 15:28:14 [main] [Log] - End Suite: Default suite
[INFO] 06-11-2023 15:29:21 [main] [Log] - Suite started: Default suite
[INFO] 06-11-2023 15:29:22 [TestNG-PoolService-0] [Log] - addBookTest test case started
[INFO] 06-11-2023 15:29:22 [TestNG-PoolService-0] [APITest] - Test started : TC01- Add book api test
[INFO] 06-11-2023 15:29:23 [TestNG-PoolService-0] [Log] - getBookByID test case started
[INFO] 06-11-2023 15:29:23 [TestNG-PoolService-0] [APITest] - Test started : TC02- Get book api test
[INFO] 06-11-2023 15:29:23 [TestNG-PoolService-0] [Log] - DeleteBook test case started
[INFO] 06-11-2023 15:29:23 [TestNG-PoolService-0] [APITest] - Test started : TC03- Delete book api test
[INFO] 06-11-2023 15:29:23 [main] [Log] - End Suite: Default suite
[INFO] 06-11-2023 19:09:27 [main] [Log] - Suite started: Suite
[INFO] 06-11-2023 19:09:28 [TestNG-PoolService-0] [Log] - addBookTest test case started
[INFO] 06-11-2023 19:09:28 [TestNG-PoolService-0] [APITest] - Test started : TC01- Add book api test
[INFO] 06-11-2023 19:09:29 [TestNG-PoolService-0] [Log] - getBookByID test case started
[INFO] 06-11-2023 19:09:29 [TestNG-PoolService-0] [APITest] - Test started : TC02- Get book api test
[INFO] 06-11-2023 19:09:30 [TestNG-PoolService-0] [Log] - DeleteBook test case started
[INFO] 06-11-2023 19:09:30 [TestNG-PoolService-0] [APITest] - Test started : TC03- Delete book api test
[INFO] 06-11-2023 19:09:30 [main] [Log] - End Suite: Suite
[INFO] 21-11-2023 16:11:35 [main] [Log] - Suite started: Suite
[INFO] 21-11-2023 16:11:36 [TestNG-PoolService-0] [baseTest] - Browser :: chrome
[INFO] 21-11-2023 16:11:39 [TestNG-PoolService-0] [baseTest] - Url launched :https://www.saucedemo.com/
[INFO] 21-11-2023 16:11:39 [TestNG-PoolService-0] [Log] - placeOrder test case started
[INFO] 21-11-2023 16:11:41 [TestNG-PoolService-0] [LoginPage] - Username entered :standard_user
[INFO] 21-11-2023 16:11:42 [TestNG-PoolService-0] [LoginPage] - Password entered :secret_sauce
[INFO] 21-11-2023 16:11:43 [TestNG-PoolService-0] [LoginPage] - Clicked on Login button
[INFO] 21-11-2023 16:11:44 [TestNG-PoolService-0] [LoginPage] - Verified title is Swag Labs
[INFO] 21-11-2023 16:11:56 [TestNG-PoolService-0] [baseTest] - Browser :: chrome
[INFO] 21-11-2023 16:11:59 [TestNG-PoolService-0] [baseTest] - Url launched :https://www.saucedemo.com/
[INFO] 21-11-2023 16:11:59 [TestNG-PoolService-0] [Log] - loginWithInValidCredentials test case started
[INFO] 21-11-2023 16:12:00 [TestNG-PoolService-0] [LoginPage] - Username entered :kshinde_user
[INFO] 21-11-2023 16:12:01 [TestNG-PoolService-0] [LoginPage] - Password entered :secret_sauce
[INFO] 21-11-2023 16:12:02 [TestNG-PoolService-0] [LoginPage] - Clicked on Login button
[INFO] 21-11-2023 16:12:02 [TestNG-PoolService-0] [LoginPage] - Verified error message displayed
[ERROR] 21-11-2023 16:12:06 [TestNG-PoolService-0] [Log] - Element is not displayed :By.id: add-to-cart-sauce-labs-backpack
[ERROR] 21-11-2023 16:12:06 [TestNG-PoolService-0] [Log] - Test case: loginWithInValidCredentials is failed.
[INFO] 21-11-2023 16:12:06 [main] [Log] - End Suite: Suite
[INFO] 21-11-2023 16:25:27 [main] [Log] - Suite started: Default Suite
[INFO] 21-11-2023 16:25:28 [TestNG-PoolService-0] [baseTest] - Browser :: chrome
[INFO] 21-11-2023 16:25:32 [TestNG-PoolService-0] [baseTest] - Url launched :https://www.saucedemo.com/
[INFO] 21-11-2023 16:25:32 [TestNG-PoolService-0] [Log] - placeOrder test case started
[INFO] 21-11-2023 16:25:33 [TestNG-PoolService-0] [LoginPage] - Username entered :standard_user
[INFO] 21-11-2023 16:25:34 [TestNG-PoolService-0] [LoginPage] - Password entered :secret_sauce
[INFO] 21-11-2023 16:25:36 [TestNG-PoolService-0] [LoginPage] - Clicked on Login button
[INFO] 21-11-2023 16:25:37 [TestNG-PoolService-0] [LoginPage] - Verified title is Swag Labs
[INFO] 21-11-2023 16:25:49 [TestNG-PoolService-0] [baseTest] - Browser :: chrome
[INFO] 21-11-2023 16:25:51 [TestNG-PoolService-0] [baseTest] - Url launched :https://www.saucedemo.com/
[INFO] 21-11-2023 16:25:52 [TestNG-PoolService-0] [Log] - loginWithInValidCredentials test case started
[INFO] 21-11-2023 16:25:53 [TestNG-PoolService-0] [LoginPage] - Username entered :kshinde_user
[INFO] 21-11-2023 16:25:54 [TestNG-PoolService-0] [LoginPage] - Password entered :secret_sauce
[INFO] 21-11-2023 16:25:55 [TestNG-PoolService-0] [LoginPage] - Clicked on Login button
[INFO] 21-11-2023 16:25:55 [TestNG-PoolService-0] [LoginPage] - Verified error message displayed
[ERROR] 21-11-2023 16:25:58 [TestNG-PoolService-0] [Log] - Element is not displayed :By.id: add-to-cart-sauce-labs-backpack
[ERROR] 21-11-2023 16:25:58 [TestNG-PoolService-0] [Log] - Test case: loginWithInValidCredentials is failed.
[INFO] 21-11-2023 16:25:59 [main] [Log] - End Suite: Default Suite
[INFO] 21-11-2023 16:27:12 [main] [Log] - Suite started: Default Suite
[INFO] 21-11-2023 16:27:12 [TestNG-PoolService-0] [baseTest] - Browser :: chrome
[INFO] 21-11-2023 16:27:16 [TestNG-PoolService-0] [baseTest] - Url launched :https://www.saucedemo.com/
[INFO] 21-11-2023 16:27:16 [TestNG-PoolService-0] [Log] - placeOrder test case started
[INFO] 21-11-2023 16:27:17 [TestNG-PoolService-0] [LoginPage] - Username entered :standard_user
[INFO] 21-11-2023 16:27:18 [TestNG-PoolService-0] [LoginPage] - Password entered :secret_sauce
[INFO] 21-11-2023 16:27:20 [TestNG-PoolService-0] [LoginPage] - Clicked on Login button
[INFO] 21-11-2023 16:27:21 [TestNG-PoolService-0] [LoginPage] - Verified title is Swag Labs
[INFO] 21-11-2023 16:27:32 [TestNG-PoolService-0] [baseTest] - Browser :: chrome
[INFO] 21-11-2023 16:27:34 [TestNG-PoolService-0] [baseTest] - Url launched :https://www.saucedemo.com/
[INFO] 21-11-2023 16:27:35 [TestNG-PoolService-0] [Log] - loginWithInValidCredentials test case started
[INFO] 21-11-2023 16:27:36 [TestNG-PoolService-0] [LoginPage] - Username entered :kshinde_user
[INFO] 21-11-2023 16:27:37 [TestNG-PoolService-0] [LoginPage] - Password entered :secret_sauce
[INFO] 21-11-2023 16:27:38 [TestNG-PoolService-0] [LoginPage] - Clicked on Login button
[INFO] 21-11-2023 16:27:38 [TestNG-PoolService-0] [LoginPage] - Verified error message displayed
[ERROR] 21-11-2023 16:27:41 [TestNG-PoolService-0] [Log] - Element is not displayed :By.id: add-to-cart-sauce-labs-backpack
[ERROR] 21-11-2023 16:27:41 [TestNG-PoolService-0] [Log] - Test case: loginWithInValidCredentials is failed.
[INFO] 21-11-2023 16:27:42 [main] [Log] - End Suite: Default Suite
[INFO] 21-11-2023 16:37:11 [main] [Log] - Suite started: Default Suite
[INFO] 21-11-2023 16:37:11 [TestNG-PoolService-0] [baseTest] - Browser :: chrome
[INFO] 21-11-2023 16:37:15 [TestNG-PoolService-0] [baseTest] - Url launched :https://www.saucedemo.com/
[INFO] 21-11-2023 16:37:15 [TestNG-PoolService-0] [Log] - placeOrder test case started
[INFO] 21-11-2023 16:37:17 [TestNG-PoolService-0] [LoginPage] - Username entered :standard_user
[INFO] 21-11-2023 16:37:18 [TestNG-PoolService-0] [LoginPage] - Password entered :secret_sauce
[INFO] 21-11-2023 16:37:19 [TestNG-PoolService-0] [LoginPage] - Clicked on Login button
[INFO] 21-11-2023 16:37:20 [TestNG-PoolService-0] [LoginPage] - Verified title is Swag Labs
[INFO] 21-11-2023 16:37:32 [TestNG-PoolService-0] [baseTest] - Browser :: chrome
[INFO] 21-11-2023 16:37:34 [TestNG-PoolService-0] [baseTest] - Url launched :https://www.saucedemo.com/
[INFO] 21-11-2023 16:37:34 [TestNG-PoolService-0] [Log] - loginWithInValidCredentials test case started
[INFO] 21-11-2023 16:37:35 [TestNG-PoolService-0] [LoginPage] - Username entered :kshinde_user
[INFO] 21-11-2023 16:37:36 [TestNG-PoolService-0] [LoginPage] - Password entered :secret_sauce
[INFO] 21-11-2023 16:37:38 [TestNG-PoolService-0] [LoginPage] - Clicked on Login button
[INFO] 21-11-2023 16:37:38 [TestNG-PoolService-0] [LoginPage] - Verified error message displayed
[ERROR] 21-11-2023 16:37:41 [TestNG-PoolService-0] [Log] - Element is not displayed :By.id: add-to-cart-sauce-labs-backpack
[ERROR] 21-11-2023 16:37:41 [TestNG-PoolService-0] [Log] - Test case: loginWithInValidCredentials is failed.
[INFO] 21-11-2023 16:37:41 [main] [Log] - End Suite: Default Suite
[INFO] 21-11-2023 16:41:39 [main] [Log] - Suite started: Default Suite
[INFO] 21-11-2023 16:41:40 [TestNG-PoolService-0] [baseTest] - Browser :: chrome
[INFO] 21-11-2023 16:41:43 [TestNG-PoolService-0] [baseTest] - Url launched :https://www.saucedemo.com/
[INFO] 21-11-2023 16:41:43 [TestNG-PoolService-0] [Log] - placeOrder test case started
[INFO] 21-11-2023 16:41:45 [TestNG-PoolService-0] [LoginPage] - Username entered :standard_user
[INFO] 21-11-2023 16:41:46 [TestNG-PoolService-0] [LoginPage] - Password entered :secret_sauce
[INFO] 21-11-2023 16:41:47 [TestNG-PoolService-0] [LoginPage] - Clicked on Login button
[INFO] 21-11-2023 16:41:48 [TestNG-PoolService-0] [LoginPage] - Verified title is Swag Labs
[INFO] 21-11-2023 16:42:00 [TestNG-PoolService-0] [baseTest] - Browser :: chrome
[INFO] 21-11-2023 16:42:02 [TestNG-PoolService-0] [baseTest] - Url launched :https://www.saucedemo.com/
[INFO] 21-11-2023 16:42:02 [TestNG-PoolService-0] [Log] - loginWithInValidCredentials test case started
[INFO] 21-11-2023 16:42:03 [TestNG-PoolService-0] [LoginPage] - Username entered :kshinde_user
[INFO] 21-11-2023 16:42:04 [TestNG-PoolService-0] [LoginPage] - Password entered :secret_sauce
[INFO] 21-11-2023 16:42:06 [TestNG-PoolService-0] [LoginPage] - Clicked on Login button
[INFO] 21-11-2023 16:42:06 [TestNG-PoolService-0] [LoginPage] - Verified error message displayed
[INFO] 21-11-2023 16:42:06 [main] [Log] - End Suite: Default Suite
